resources:
  - ../../../rbac
  - ../../../webhook

namespace: '{{ .Release.Namespace }}'

namePrefix: '{{ template "accurate.fullname" . }}-'

patches:
  - path: webhookcainjection_patch.yaml

components:
  - ../../components/common-labels
