apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-sealedsecrets
rules:
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: innu-read-sealedsecrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-sealedsecrets
subjects:
- kind: ServiceAccount
  name: innu-controller-manager
  namespace: innu
