resources:
- ../config/default

patchesStrategicMerge:
- manager_patch.yaml

configMapGenerator:
- name: accurate-config
  namespace: accurate
  files:
  - config.yaml

images:
- name: ghcr.io/cybozu-go/accurate
  newName: accurate
  newTag: dev
