apiVersion: apps/v1
kind: Deployment
metadata:
  name: accurate-controller-manager
  namespace: accurate
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - --zap-log-level=5
