apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: '{{ .Values.crds.keep | ternary "keep" "delete" }}'
  name: subnamespaces.accurate.cybozu.com
