# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/accurate.cybozu.com_subnamespaces.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
- path: patches/cainjection_in_subnamespaces.yaml
- path: patches/fix-crd.yaml
- path: patches/webhook_in_subnamespaces.yaml

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
