name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'
jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - uses: ./.github/actions/aqua
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: make release-build
  test:
    name: Small tests
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - uses: ./.github/actions/aqua
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: make test
    - run: make check-generate
    - run: make envtest
  e2e:
    name: End-to-End Tests
    strategy:
      matrix:
        k8s-version:
        - v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027 # renovate: kindest/node
        - v1.31.4@sha256:2cb39f7295fe7eafee0842b1052a599a4fb0f8bcf3f83d96c7f4864c357c6c30 # renovate: kindest/node
        - v1.30.8@sha256:17cd608b3971338d9180b00776cb766c50d0a0b6b904ab4ff52fd3fc5c6369bf # renovate: kindest/node
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true
    - uses: ./.github/actions/aqua
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: make start KUBERNETES_VERSION=${{ matrix.k8s-version }}
      working-directory: e2e
    - run: make test
      working-directory: e2e
    - run: make logs
      working-directory: e2e
      if: always()
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs-${{ replace(matrix.k8s-version, ':', '-') }}.tar.gz
        path: e2e/logs.tar.gz
