name: Lint and Test Charts
on:
  pull_request:
    paths:
      - "charts/**"
      - '!**.md'

jobs:
  lint-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Set up buildkit builder for multiarch
        run: |
          docker buildx create --name=multiarch-builder --driver docker-container --driver-opt network=host
          docker buildx use multiarch-builder

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create kind cluster with registry
        id: kind
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          node_image: kindest/node:v1.31.4
          registry: true
          registry_name: kind-registry
          registry_port: 5000

      - name: Apply cert-manager
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml
          kubectl -n cert-manager wait --for=condition=available --timeout=180s --all deployments

      - name: Wait for kind registry to be ready
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          echo "Waiting for kind registry to be ready..."
          for i in {1..30}; do
            if curl -f http://localhost:5000/v2/ >/dev/null 2>&1; then
              echo "Registry is ready"
              break
            fi
            echo "Waiting for registry... (attempt $i/30)"
            sleep 2
          done

      - name: Build and push multiarch image
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --output type=registry,name=localhost:5000/accurate:dev,push=true,registry.insecure=true,compression=zstd \
            .

      - name: Prepare values.yaml for testing
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          mkdir -p charts/accurate/ci/
          cat > charts/accurate/ci/ci-values.yaml <<EOF
          image:
            repository: localhost:5000/accurate
            tag: dev
            pullPolicy: Always
          EOF

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --config ct.yaml
