name: Release
on:
  push:
    tags:
    - 'v*'
env:
  go-version: 1.18
jobs:
  image:
    name: Push Container Image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build images
      run: |
        docker build -t accurate:dev .
    - name: Login to ghcr.io
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Push images
      run: |
        TAG=${GITHUB_REF#refs/tags/v}
        docker tag accurate:dev ghcr.io/cybozu-go/accurate:$TAG
        docker push ghcr.io/cybozu-go/accurate:$TAG
  release:
    name: Release on GitHub
    needs: image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.go-version }}
    - name: GoReleaser
      # v3.0.0 https://github.com/goreleaser/goreleaser-action/releases/tag/v3.0.0
      uses: goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef
      with:
        distribution: goreleaser
        version: v0.180.3
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update new version in krew-index
      # v0.0.43 https://github.com/rajatjindal/krew-release-bot/releases/tag/v0.0.43
      uses: rajatjindal/krew-release-bot@92da038bbf995803124a8e50ebd438b2f37bbbb0
