name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  image:
    name: Push Container Image
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build images
      run: |
        docker build -t accurate:dev .
    - name: Login to ghcr.io
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Push images
      run: |
        TAG=${GITHUB_REF#refs/tags/v}
        docker tag accurate:dev ghcr.io/cybozu-go/accurate:$TAG
        docker push ghcr.io/cybozu-go/accurate:$TAG
  release:
    name: Release on GitHub
    needs: image
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true
    - name: GoReleaser
      # v4.2.0 https://github.com/goreleaser/goreleaser-action/releases/tag/v4.2.0
      uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b
      with:
        distribution: goreleaser
        version: v1.15.2
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update new version in krew-index
      # v0.0.43 https://github.com/rajatjindal/krew-release-bot/releases/tag/v0.0.43
      uses: rajatjindal/krew-release-bot@92da038bbf995803124a8e50ebd438b2f37bbbb0
