name: Renovate
on:
  schedule:
    - cron: '0 10 * * 1'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@e084b5ac6fd201023db6dd7743aec023babb02c8 # renovate v41.0.13
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
