apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: accurate/accurate-serving-cert
  name: subnamespaces.accurate.cybozu.com
spec:
  conversion:
    webhook:
      clientConfig:
        service:
          namespace: accurate
          name: accurate-webhook-service
